[DATA]
DATA_PATH='data'
TRAIN_FOLDER_NAME='train'
VALID_FOLDER_NAME='valid'
TEST_FOLDER_NAME='test'
CLASS_MODEL_PATH='models\class_model.pth'


[TRAIN]
EPOCHS=10
LEARNING_RATE=0.0003
BATCH_SIZE=64
INPUT_LABEL='input'
OUTPUT_LABEL='output'